services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: nasa-app-backend
    ports:
      - "${PORT}:${PORT}"  # Use the port from .env file
    environment:
      - PORT=${PORT}  # Make sure Docker uses the PORT from .env
    env_file:
      - ./.env   # Load the .env file
    volumes:
      - .:/app
    command: npm start
